spring:
  application:
    name: learning-online-admin
  # 上传文件设置
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    name: dataSource1                                                             #如果存在多个数据源，监控的时候可以通过名字来区分开来。如果没有配置，将会生成一个名字，格式是："DataSource-" + System.identityHashCode(this)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.31.24:3306/learing-online?serverTimezone=UTC&characterEncoding=utf-8
#    url: jdbc:mysql://127.0.0.1:3306/learing-online?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    # druid配置
    druid:
      initialSize: 10                                                              #初始化连接个数
      minIdle: 10                                                                  #最小空闲连接个数
      maxActive: 100                                                               #最大连接个数
      maxWait: 60000                                                               #获取连接时最大等待时间，单位毫秒。
      timeBetweenEvictionRunsMillis: 60000                                         #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000                                            #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: select 'x'                                                  #用来检测连接是否有效的sql，要求是一个查询语句。
      testWhileIdle: true                                                          #建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: true                                                           #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false                                                          #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: false                                                #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxPoolPreparedStatementPerConnectionSize: -1                                #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      filters: stat,wall                                                           #通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat，日志用的filter:log4j，防御sql注入的filter:wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: false                                               # 合并多个DruidDataSource的监控数据
  # redis 配置
#  redis:
#    database: 0                                                                    # Redis数据库索引（默认为0）
#    host: 106.15.205.51
#    port: 6379
#    password:
#    redis:
#      pool:
#        max-active: 200                                                            # 最大连接数
#        max-wait: -1                                                               # 最大阻塞等待时间
#        max-idle: 10                                                               # 最大空闲连接
#        min-idle: 0                                                                # 最小空闲连接
#    timeout: 1000                                                                  # 连接超时时间



# Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true                                              # 启用驼峰命名
#  config-location: classpath:mybatis/mybatis-config.xml # 指定全局配置文件的位置
#  mapper-locations: classpath:mybatis/mapper/*.xml      # 指定sql映射文件的位置

# 服务器配置
server:
  port: 8081

# 日志
logging:
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  file:
    name: applicationRun.log

# 基础框架配置
bossoft:
  # Swagger2配置
  swagger2:
    basePackage: com.lyy
    title: 智多星平台api文档
    description: 简单优雅的restful风格
    termsOfServiceUrl: https://blog.csdn.net/l1336037686
    version: v1.0
  # Cdn配置
  cdn:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIeh9HSUIOFLPX
    accessKeySelect: t8cacC2tjcYGvTmTStTXYLsJeEdnwG
    bucketName: lgx-tvt
    imageFolder: image/
    videoFolder: video/
    resourceFolder: resource/
  # Sms短信服务配置
  sms:
    defaultConnectTimeout: sun.net.client.defaultConnectTimeout
    defaultReadTimeout: sun.net.client.defaultReadTimeout
    timeout: 20000
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    accessKeyId: LTAIGTcfXJNBfkTM
    accessKeySecret: jS1vjMOQfV35Jbo7ULDNRiyz5qZ2mM
    signName: SaltFish
    templateCode: SMS_172738481
    regionId: cn-hangzhou
    smsCodeLength: 6
  # Email邮件服务
  email:
    endPoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAIGTcfXJNBfkTM
    accessKeySelect: jS1vjMOQfV35Jbo7ULDNRiyz5qZ2mM
    accountName: postmaste@pkying.top
    tagName: postmaster
    fromAlias: 智多星
    toAddress: true
    subject: 智多星
    emailHtmlBody: <h1 style="color:red;">验证码：{{code}}</h1>
    regionId: cn-hangzhou
    emailCodeLength: 6
